WIDTH = 1024
HEIGHT = 500
#1024/768

TILESIZE = 64
MAPWIDTH = WIDTH/TILESIZE
MAPHEIGHT = HEIGHT/TILESIZE

FPS = 60

TITLE = "Game"

#player
PLAYER_SPEED = 250
PLAYER_IMAGE = "player.png"
PLAYER_IMAGE_ROT = "player_rot.png"
PLAYER_ATTACK_RATE = 300
PLAYER_HEALTH = 100

#enemy
ENEMY_ROT_SPEED = 25
ENEMY1_IMG = "Sentinel.png"
ENEMY1_2_IMG = "Sentinel.png"
ENEMY_HEIGHT = 96
ENEMY_WIDTH = 96

SHOOT1_SPRITE = "shoot1.png"
SHOOT_LIFE_TIME = 5000
SHOOT_VEL = 500
SHOOT_DAMAGE = 20
