WIDTH = 1024
HEIGHT = 500
#1024/768

TILESIZE = 64
MAPWIDTH = WIDTH/TILESIZE
MAPHEIGHT = HEIGHT/TILESIZE

FPS = 60

TITLE = "Game"

#player
PLAYER_SPEED = 250
PLAYER_IMAGE = "player.png"
PLAYER_WIDTH = 64
PLAYER_HEIGHT = 64
PLAYER_IMAGE_ROT = "player_rot.png"
PLAYER_ATTACK_RATE = 300
PLAYER_HEALTH = 100

#enemy
ENEMY_ROT_SPEED = 25
ENEMY1_IMG = "Sentinel.png"
ENEMY1_2_IMG = "Sentinel.png"
ENEMY_HEIGHT = 96
ENEMY_WIDTH = 96

SHOOT1_SPRITE = "shoot1.png"
SHOOT3_SPRITE = "shoot3.png"
SHOOT3_1_SPRITE = "shoot3_1.png"
SHOOT_LIFE_TIME = 5000
SHOOT_VEL = 500
SHOOT_DAMAGE = 20

PILHA_SUCATA_IMG = "pile.png"
PILHA_FERRAMENTA_IMG = "pile2.png"

BOSS1_IMG = "boss.png"
BOSS1_WIDTH = 385
BOSS1_HEIGHT = 370

PLAYER_INV_IMG = "player_inv.png"
ITEM_WIDTH = 46
ITEM_HEIGHT = 26
METAL_IMG = "metal.png"
PERNA_IMG = "perna.png"
